### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by Quarkrus**
Formatted & optimized ru translate and sightly corrected

### CODE REVIEW

**Comment by AzureDoom** [comment]
Thanks! Will review and merge in the next day or so.

**Comment by mpustovoi** [comment]
@Quarkrus what did you edit it with?

**Comment by Quarkrus** [comment]
> @Quarkrus what did you edit it with?

I just removed all spaces and indents between lines and replaced all letters with a format understandable for Unix ASCII
Mainly used a notepad and internet resources like popular JSON Formatter and Text To Sex Formatter

**Comment by mpustovoi** [comment]
> I just removed all spaces and indents between lines

Why was it necessary? The language file weight is still so low in relation to the entire mod file. (If this is a weight chase after all)

> replaced all letters with a format understandable for Unix ASCII

Does Minecraft have problems understanding the characters of the Russian alphabet?

**Comment by Quarkrus** [comment]
> Why was it necessary? The language file weight is still so low in relation to the entire mod file. (If this is a weight chase after all)
> 
Repeated as was in English and other language files

> Does Minecraft have problems understanding the characters of the Russian alphabet?
>
One word - squares
And this is even with the CRLF format, for some reason in this mod it does not work and forcibly shows only squares

**Pull request merged**
